version: "3"
services: 
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: app
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: npm run dev
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - db_data:/var/lib/posrgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db_data: {}
networks:
  backend:
